/*
 * generated by Xtext
 */
package emn.a1.ui.contentassist

import emn.a1.ui.contentassist.AbstractElascriptProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class ElascriptProposalProvider extends AbstractElascriptProposalProvider {
}
