/*
 * generated by Xtext
 */
package org.elascript;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class ElascriptUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return org.elascript.ui.internal.ElascriptActivator.getInstance().getInjector("org.elascript.Elascript");
	}
	
}
