/*
 * generated by Xtext
 */
package emn.a1;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ElascriptRuntimeModule extends emn.a1.AbstractElascriptRuntimeModule {

}
