/*
 * generated by Xtext
 */
package emn.a1.elascript;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class ElascriptUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return emn.a1.elascript.ui.internal.ElascriptActivator.getInstance().getInjector("emn.a1.elascript.Elascript");
	}
	
}
