/*
* generated by Xtext
*/
package emn.a1.elascript.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ElascriptAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("emn/a1/elascript/parser/antlr/internal/InternalElascript.tokens");
	}
}
