/*
* generated by Xtext
*/
package emn.a1.elascript.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class ElascriptGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class ScriptElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Script");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cBeginScriptAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cBeginScriptBeginScriptParserRuleCall_0_0 = (RuleCall)cBeginScriptAssignment_0.eContents().get(0);
		private final Assignment cScriptStatementAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cScriptStatementStatementListParserRuleCall_1_0 = (RuleCall)cScriptStatementAssignment_1.eContents().get(0);
		private final Assignment cEndScriptAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cEndScriptEndScriptParserRuleCall_2_0 = (RuleCall)cEndScriptAssignment_2.eContents().get(0);
		
		//Script:
		//	BeginScript=BeginScript scriptStatement=StatementList EndScript=EndScript;
		public ParserRule getRule() { return rule; }

		//BeginScript=BeginScript scriptStatement=StatementList EndScript=EndScript
		public Group getGroup() { return cGroup; }

		//BeginScript=BeginScript
		public Assignment getBeginScriptAssignment_0() { return cBeginScriptAssignment_0; }

		//BeginScript
		public RuleCall getBeginScriptBeginScriptParserRuleCall_0_0() { return cBeginScriptBeginScriptParserRuleCall_0_0; }

		//scriptStatement=StatementList
		public Assignment getScriptStatementAssignment_1() { return cScriptStatementAssignment_1; }

		//StatementList
		public RuleCall getScriptStatementStatementListParserRuleCall_1_0() { return cScriptStatementStatementListParserRuleCall_1_0; }

		//EndScript=EndScript
		public Assignment getEndScriptAssignment_2() { return cEndScriptAssignment_2; }

		//EndScript
		public RuleCall getEndScriptEndScriptParserRuleCall_2_0() { return cEndScriptEndScriptParserRuleCall_2_0; }
	}

	public class BeginScriptElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "BeginScript");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final Keyword cNameBeginKeyword_0 = (Keyword)cNameAssignment.eContents().get(0);
		
		//BeginScript:
		//	name="begin";
		public ParserRule getRule() { return rule; }

		//name="begin"
		public Assignment getNameAssignment() { return cNameAssignment; }

		//"begin"
		public Keyword getNameBeginKeyword_0() { return cNameBeginKeyword_0; }
	}

	public class EndScriptElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EndScript");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final Keyword cNameEndKeyword_0 = (Keyword)cNameAssignment.eContents().get(0);
		
		//EndScript:
		//	name="end";
		public ParserRule getRule() { return rule; }

		//name="end"
		public Assignment getNameAssignment() { return cNameAssignment; }

		//"end"
		public Keyword getNameEndKeyword_0() { return cNameEndKeyword_0; }
	}

	public class StatementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Statement");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cCommandParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cParallelParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Statement:
		//	Command | Parallel;
		public ParserRule getRule() { return rule; }

		//Command | Parallel
		public Alternatives getAlternatives() { return cAlternatives; }

		//Command
		public RuleCall getCommandParserRuleCall_0() { return cCommandParserRuleCall_0; }

		//Parallel
		public RuleCall getParallelParserRuleCall_1() { return cParallelParserRuleCall_1; }
	}

	public class ParallelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Parallel");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cBeginParallelAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cBeginParallelBeginParallelParserRuleCall_0_0 = (RuleCall)cBeginParallelAssignment_0.eContents().get(0);
		private final Assignment cStatementListsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cStatementListsStatementListParserRuleCall_1_0 = (RuleCall)cStatementListsAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final RuleCall cPARALLEL_SEPARATORTerminalRuleCall_2_0 = (RuleCall)cGroup_2.eContents().get(0);
		private final Assignment cStatementListsAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cStatementListsStatementListParserRuleCall_2_1_0 = (RuleCall)cStatementListsAssignment_2_1.eContents().get(0);
		private final Assignment cEndParallelAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cEndParallelEndParallelParserRuleCall_3_0 = (RuleCall)cEndParallelAssignment_3.eContents().get(0);
		
		//Parallel:
		//	BeginParallel=BeginParallel statementLists+=StatementList (PARALLEL_SEPARATOR statementLists+=StatementList)+
		//	EndParallel=EndParallel;
		public ParserRule getRule() { return rule; }

		//BeginParallel=BeginParallel statementLists+=StatementList (PARALLEL_SEPARATOR statementLists+=StatementList)+
		//EndParallel=EndParallel
		public Group getGroup() { return cGroup; }

		//BeginParallel=BeginParallel
		public Assignment getBeginParallelAssignment_0() { return cBeginParallelAssignment_0; }

		//BeginParallel
		public RuleCall getBeginParallelBeginParallelParserRuleCall_0_0() { return cBeginParallelBeginParallelParserRuleCall_0_0; }

		//statementLists+=StatementList
		public Assignment getStatementListsAssignment_1() { return cStatementListsAssignment_1; }

		//StatementList
		public RuleCall getStatementListsStatementListParserRuleCall_1_0() { return cStatementListsStatementListParserRuleCall_1_0; }

		//(PARALLEL_SEPARATOR statementLists+=StatementList)+
		public Group getGroup_2() { return cGroup_2; }

		//PARALLEL_SEPARATOR
		public RuleCall getPARALLEL_SEPARATORTerminalRuleCall_2_0() { return cPARALLEL_SEPARATORTerminalRuleCall_2_0; }

		//statementLists+=StatementList
		public Assignment getStatementListsAssignment_2_1() { return cStatementListsAssignment_2_1; }

		//StatementList
		public RuleCall getStatementListsStatementListParserRuleCall_2_1_0() { return cStatementListsStatementListParserRuleCall_2_1_0; }

		//EndParallel=EndParallel
		public Assignment getEndParallelAssignment_3() { return cEndParallelAssignment_3; }

		//EndParallel
		public RuleCall getEndParallelEndParallelParserRuleCall_3_0() { return cEndParallelEndParallelParserRuleCall_3_0; }
	}

	public class BeginParallelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "BeginParallel");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final Keyword cNameLeftSquareBracketKeyword_0 = (Keyword)cNameAssignment.eContents().get(0);
		
		//BeginParallel:
		//	name="[";
		public ParserRule getRule() { return rule; }

		//name="["
		public Assignment getNameAssignment() { return cNameAssignment; }

		//"["
		public Keyword getNameLeftSquareBracketKeyword_0() { return cNameLeftSquareBracketKeyword_0; }
	}

	public class EndParallelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EndParallel");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final Keyword cNameRightSquareBracketKeyword_0 = (Keyword)cNameAssignment.eContents().get(0);
		
		//EndParallel:
		//	name="]";
		public ParserRule getRule() { return rule; }

		//name="]"
		public Assignment getNameAssignment() { return cNameAssignment; }

		//"]"
		public Keyword getNameRightSquareBracketKeyword_0() { return cNameRightSquareBracketKeyword_0; }
	}

	public class StatementListElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "StatementList");
		private final Assignment cStatementsAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cStatementsStatementParserRuleCall_0 = (RuleCall)cStatementsAssignment.eContents().get(0);
		
		//StatementList:
		//	statements+=Statement+;
		public ParserRule getRule() { return rule; }

		//statements+=Statement+
		public Assignment getStatementsAssignment() { return cStatementsAssignment; }

		//Statement
		public RuleCall getStatementsStatementParserRuleCall_0() { return cStatementsStatementParserRuleCall_0; }
	}

	public class CommandElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Command");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Alternatives cAlternatives_0 = (Alternatives)cGroup.eContents().get(0);
		private final RuleCall cScaleFunctionParserRuleCall_0_0 = (RuleCall)cAlternatives_0.eContents().get(0);
		private final RuleCall cGenericFunctionParserRuleCall_0_1 = (RuleCall)cAlternatives_0.eContents().get(1);
		private final RuleCall cWaitFunctionParserRuleCall_0_2 = (RuleCall)cAlternatives_0.eContents().get(2);
		private final RuleCall cLPTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Assignment cParamsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cParamsParamParserRuleCall_2_0 = (RuleCall)cParamsAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final RuleCall cCOMMATerminalRuleCall_3_0 = (RuleCall)cGroup_3.eContents().get(0);
		private final Assignment cParamsAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cParamsParamParserRuleCall_3_1_0 = (RuleCall)cParamsAssignment_3_1.eContents().get(0);
		private final RuleCall cRPTerminalRuleCall_4 = (RuleCall)cGroup.eContents().get(4);
		private final RuleCall cSEQUENTIAL_SEPARATORTerminalRuleCall_5 = (RuleCall)cGroup.eContents().get(5);
		
		//Command:
		//	(ScaleFunction | GenericFunction | WaitFunction) LP params+=Param (COMMA params+=Param)* RP SEQUENTIAL_SEPARATOR;
		public ParserRule getRule() { return rule; }

		//(ScaleFunction | GenericFunction | WaitFunction) LP params+=Param (COMMA params+=Param)* RP SEQUENTIAL_SEPARATOR
		public Group getGroup() { return cGroup; }

		//ScaleFunction | GenericFunction | WaitFunction
		public Alternatives getAlternatives_0() { return cAlternatives_0; }

		//ScaleFunction
		public RuleCall getScaleFunctionParserRuleCall_0_0() { return cScaleFunctionParserRuleCall_0_0; }

		//GenericFunction
		public RuleCall getGenericFunctionParserRuleCall_0_1() { return cGenericFunctionParserRuleCall_0_1; }

		//WaitFunction
		public RuleCall getWaitFunctionParserRuleCall_0_2() { return cWaitFunctionParserRuleCall_0_2; }

		//LP
		public RuleCall getLPTerminalRuleCall_1() { return cLPTerminalRuleCall_1; }

		//params+=Param
		public Assignment getParamsAssignment_2() { return cParamsAssignment_2; }

		//Param
		public RuleCall getParamsParamParserRuleCall_2_0() { return cParamsParamParserRuleCall_2_0; }

		//(COMMA params+=Param)*
		public Group getGroup_3() { return cGroup_3; }

		//COMMA
		public RuleCall getCOMMATerminalRuleCall_3_0() { return cCOMMATerminalRuleCall_3_0; }

		//params+=Param
		public Assignment getParamsAssignment_3_1() { return cParamsAssignment_3_1; }

		//Param
		public RuleCall getParamsParamParserRuleCall_3_1_0() { return cParamsParamParserRuleCall_3_1_0; }

		//RP
		public RuleCall getRPTerminalRuleCall_4() { return cRPTerminalRuleCall_4; }

		//SEQUENTIAL_SEPARATOR
		public RuleCall getSEQUENTIAL_SEPARATORTerminalRuleCall_5() { return cSEQUENTIAL_SEPARATORTerminalRuleCall_5; }
	}

	public class ScaleFunctionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ScaleFunction");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cScaleInInfraParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cScaleOutInfraParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cScaleUpInfraParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cScaleDownInfraParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cScaleInSoftParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cScaleOutSoftParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		private final RuleCall cScaleUpSoftParserRuleCall_6 = (RuleCall)cAlternatives.eContents().get(6);
		private final RuleCall cScaleDownSoftParserRuleCall_7 = (RuleCall)cAlternatives.eContents().get(7);
		
		//ScaleFunction:
		//	ScaleInInfra | ScaleOutInfra | ScaleUpInfra | ScaleDownInfra | ScaleInSoft | ScaleOutSoft | ScaleUpSoft |
		//	ScaleDownSoft;
		public ParserRule getRule() { return rule; }

		//ScaleInInfra | ScaleOutInfra | ScaleUpInfra | ScaleDownInfra | ScaleInSoft | ScaleOutSoft | ScaleUpSoft | ScaleDownSoft
		public Alternatives getAlternatives() { return cAlternatives; }

		//ScaleInInfra
		public RuleCall getScaleInInfraParserRuleCall_0() { return cScaleInInfraParserRuleCall_0; }

		//ScaleOutInfra
		public RuleCall getScaleOutInfraParserRuleCall_1() { return cScaleOutInfraParserRuleCall_1; }

		//ScaleUpInfra
		public RuleCall getScaleUpInfraParserRuleCall_2() { return cScaleUpInfraParserRuleCall_2; }

		//ScaleDownInfra
		public RuleCall getScaleDownInfraParserRuleCall_3() { return cScaleDownInfraParserRuleCall_3; }

		//ScaleInSoft
		public RuleCall getScaleInSoftParserRuleCall_4() { return cScaleInSoftParserRuleCall_4; }

		//ScaleOutSoft
		public RuleCall getScaleOutSoftParserRuleCall_5() { return cScaleOutSoftParserRuleCall_5; }

		//ScaleUpSoft
		public RuleCall getScaleUpSoftParserRuleCall_6() { return cScaleUpSoftParserRuleCall_6; }

		//ScaleDownSoft
		public RuleCall getScaleDownSoftParserRuleCall_7() { return cScaleDownSoftParserRuleCall_7; }
	}

	public class WaitFunctionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "WaitFunction");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final Keyword cNameWaitKeyword_0 = (Keyword)cNameAssignment.eContents().get(0);
		
		//WaitFunction:
		//	name="wait";
		public ParserRule getRule() { return rule; }

		//name="wait"
		public Assignment getNameAssignment() { return cNameAssignment; }

		//"wait"
		public Keyword getNameWaitKeyword_0() { return cNameWaitKeyword_0; }
	}

	public class GenericFunctionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "GenericFunction");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_0 = (RuleCall)cNameAssignment.eContents().get(0);
		
		//GenericFunction:
		//	name=ID;
		public ParserRule getRule() { return rule; }

		//name=ID
		public Assignment getNameAssignment() { return cNameAssignment; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_0() { return cNameIDTerminalRuleCall_0; }
	}

	public class ScaleInInfraElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ScaleInInfra");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final Keyword cNameScaleInInfraKeyword_0 = (Keyword)cNameAssignment.eContents().get(0);
		
		//ScaleInInfra:
		//	name="scaleInInfra";
		public ParserRule getRule() { return rule; }

		//name="scaleInInfra"
		public Assignment getNameAssignment() { return cNameAssignment; }

		//"scaleInInfra"
		public Keyword getNameScaleInInfraKeyword_0() { return cNameScaleInInfraKeyword_0; }
	}

	public class ScaleOutInfraElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ScaleOutInfra");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final Keyword cNameScaleOutInfraKeyword_0 = (Keyword)cNameAssignment.eContents().get(0);
		
		//ScaleOutInfra:
		//	name="scaleOutInfra";
		public ParserRule getRule() { return rule; }

		//name="scaleOutInfra"
		public Assignment getNameAssignment() { return cNameAssignment; }

		//"scaleOutInfra"
		public Keyword getNameScaleOutInfraKeyword_0() { return cNameScaleOutInfraKeyword_0; }
	}

	public class ScaleUpInfraElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ScaleUpInfra");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final Keyword cNameScaleUpInfraKeyword_0 = (Keyword)cNameAssignment.eContents().get(0);
		
		//ScaleUpInfra:
		//	name="scaleUpInfra";
		public ParserRule getRule() { return rule; }

		//name="scaleUpInfra"
		public Assignment getNameAssignment() { return cNameAssignment; }

		//"scaleUpInfra"
		public Keyword getNameScaleUpInfraKeyword_0() { return cNameScaleUpInfraKeyword_0; }
	}

	public class ScaleDownInfraElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ScaleDownInfra");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final Keyword cNameScaleDownInfraKeyword_0 = (Keyword)cNameAssignment.eContents().get(0);
		
		//ScaleDownInfra:
		//	name="scaleDownInfra";
		public ParserRule getRule() { return rule; }

		//name="scaleDownInfra"
		public Assignment getNameAssignment() { return cNameAssignment; }

		//"scaleDownInfra"
		public Keyword getNameScaleDownInfraKeyword_0() { return cNameScaleDownInfraKeyword_0; }
	}

	public class ScaleInSoftElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ScaleInSoft");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final Keyword cNameScaleInSoftKeyword_0 = (Keyword)cNameAssignment.eContents().get(0);
		
		//ScaleInSoft:
		//	name="scaleInSoft";
		public ParserRule getRule() { return rule; }

		//name="scaleInSoft"
		public Assignment getNameAssignment() { return cNameAssignment; }

		//"scaleInSoft"
		public Keyword getNameScaleInSoftKeyword_0() { return cNameScaleInSoftKeyword_0; }
	}

	public class ScaleOutSoftElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ScaleOutSoft");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final Keyword cNameScaleOutSoftKeyword_0 = (Keyword)cNameAssignment.eContents().get(0);
		
		//ScaleOutSoft:
		//	name="scaleOutSoft";
		public ParserRule getRule() { return rule; }

		//name="scaleOutSoft"
		public Assignment getNameAssignment() { return cNameAssignment; }

		//"scaleOutSoft"
		public Keyword getNameScaleOutSoftKeyword_0() { return cNameScaleOutSoftKeyword_0; }
	}

	public class ScaleUpSoftElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ScaleUpSoft");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final Keyword cNameScaleUpSoftKeyword_0 = (Keyword)cNameAssignment.eContents().get(0);
		
		//ScaleUpSoft:
		//	name="scaleUpSoft";
		public ParserRule getRule() { return rule; }

		//name="scaleUpSoft"
		public Assignment getNameAssignment() { return cNameAssignment; }

		//"scaleUpSoft"
		public Keyword getNameScaleUpSoftKeyword_0() { return cNameScaleUpSoftKeyword_0; }
	}

	public class ScaleDownSoftElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ScaleDownSoft");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final Keyword cNameScaleDownSoftKeyword_0 = (Keyword)cNameAssignment.eContents().get(0);
		
		//ScaleDownSoft:
		//	name="scaleDownSoft";
		public ParserRule getRule() { return rule; }

		//name="scaleDownSoft"
		public Assignment getNameAssignment() { return cNameAssignment; }

		//"scaleDownSoft"
		public Keyword getNameScaleDownSoftKeyword_0() { return cNameScaleDownSoftKeyword_0; }
	}

	public class ParamElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Param");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueINTTerminalRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//Param:
		//	value=INT;
		public ParserRule getRule() { return rule; }

		//value=INT
		public Assignment getValueAssignment() { return cValueAssignment; }

		//INT
		public RuleCall getValueINTTerminalRuleCall_0() { return cValueINTTerminalRuleCall_0; }
	}
	
	
	private final ScriptElements pScript;
	private final BeginScriptElements pBeginScript;
	private final EndScriptElements pEndScript;
	private final StatementElements pStatement;
	private final ParallelElements pParallel;
	private final BeginParallelElements pBeginParallel;
	private final EndParallelElements pEndParallel;
	private final StatementListElements pStatementList;
	private final CommandElements pCommand;
	private final ScaleFunctionElements pScaleFunction;
	private final WaitFunctionElements pWaitFunction;
	private final GenericFunctionElements pGenericFunction;
	private final ScaleInInfraElements pScaleInInfra;
	private final ScaleOutInfraElements pScaleOutInfra;
	private final ScaleUpInfraElements pScaleUpInfra;
	private final ScaleDownInfraElements pScaleDownInfra;
	private final ScaleInSoftElements pScaleInSoft;
	private final ScaleOutSoftElements pScaleOutSoft;
	private final ScaleUpSoftElements pScaleUpSoft;
	private final ScaleDownSoftElements pScaleDownSoft;
	private final ParamElements pParam;
	private final TerminalRule tPARALLEL_SEPARATOR;
	private final TerminalRule tLP;
	private final TerminalRule tRP;
	private final TerminalRule tLETTER;
	private final TerminalRule tNUMBER;
	private final TerminalRule tSEQUENTIAL_SEPARATOR;
	private final TerminalRule tCOMMA;
	
	private final Grammar grammar;

	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public ElascriptGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pScript = new ScriptElements();
		this.pBeginScript = new BeginScriptElements();
		this.pEndScript = new EndScriptElements();
		this.pStatement = new StatementElements();
		this.pParallel = new ParallelElements();
		this.pBeginParallel = new BeginParallelElements();
		this.pEndParallel = new EndParallelElements();
		this.pStatementList = new StatementListElements();
		this.pCommand = new CommandElements();
		this.pScaleFunction = new ScaleFunctionElements();
		this.pWaitFunction = new WaitFunctionElements();
		this.pGenericFunction = new GenericFunctionElements();
		this.pScaleInInfra = new ScaleInInfraElements();
		this.pScaleOutInfra = new ScaleOutInfraElements();
		this.pScaleUpInfra = new ScaleUpInfraElements();
		this.pScaleDownInfra = new ScaleDownInfraElements();
		this.pScaleInSoft = new ScaleInSoftElements();
		this.pScaleOutSoft = new ScaleOutSoftElements();
		this.pScaleUpSoft = new ScaleUpSoftElements();
		this.pScaleDownSoft = new ScaleDownSoftElements();
		this.pParam = new ParamElements();
		this.tPARALLEL_SEPARATOR = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "PARALLEL_SEPARATOR");
		this.tLP = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "LP");
		this.tRP = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "RP");
		this.tLETTER = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "LETTER");
		this.tNUMBER = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "NUMBER");
		this.tSEQUENTIAL_SEPARATOR = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "SEQUENTIAL_SEPARATOR");
		this.tCOMMA = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "COMMA");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("emn.a1.elascript.Elascript".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Script:
	//	BeginScript=BeginScript scriptStatement=StatementList EndScript=EndScript;
	public ScriptElements getScriptAccess() {
		return pScript;
	}
	
	public ParserRule getScriptRule() {
		return getScriptAccess().getRule();
	}

	//BeginScript:
	//	name="begin";
	public BeginScriptElements getBeginScriptAccess() {
		return pBeginScript;
	}
	
	public ParserRule getBeginScriptRule() {
		return getBeginScriptAccess().getRule();
	}

	//EndScript:
	//	name="end";
	public EndScriptElements getEndScriptAccess() {
		return pEndScript;
	}
	
	public ParserRule getEndScriptRule() {
		return getEndScriptAccess().getRule();
	}

	//Statement:
	//	Command | Parallel;
	public StatementElements getStatementAccess() {
		return pStatement;
	}
	
	public ParserRule getStatementRule() {
		return getStatementAccess().getRule();
	}

	//Parallel:
	//	BeginParallel=BeginParallel statementLists+=StatementList (PARALLEL_SEPARATOR statementLists+=StatementList)+
	//	EndParallel=EndParallel;
	public ParallelElements getParallelAccess() {
		return pParallel;
	}
	
	public ParserRule getParallelRule() {
		return getParallelAccess().getRule();
	}

	//BeginParallel:
	//	name="[";
	public BeginParallelElements getBeginParallelAccess() {
		return pBeginParallel;
	}
	
	public ParserRule getBeginParallelRule() {
		return getBeginParallelAccess().getRule();
	}

	//EndParallel:
	//	name="]";
	public EndParallelElements getEndParallelAccess() {
		return pEndParallel;
	}
	
	public ParserRule getEndParallelRule() {
		return getEndParallelAccess().getRule();
	}

	//StatementList:
	//	statements+=Statement+;
	public StatementListElements getStatementListAccess() {
		return pStatementList;
	}
	
	public ParserRule getStatementListRule() {
		return getStatementListAccess().getRule();
	}

	//Command:
	//	(ScaleFunction | GenericFunction | WaitFunction) LP params+=Param (COMMA params+=Param)* RP SEQUENTIAL_SEPARATOR;
	public CommandElements getCommandAccess() {
		return pCommand;
	}
	
	public ParserRule getCommandRule() {
		return getCommandAccess().getRule();
	}

	//ScaleFunction:
	//	ScaleInInfra | ScaleOutInfra | ScaleUpInfra | ScaleDownInfra | ScaleInSoft | ScaleOutSoft | ScaleUpSoft |
	//	ScaleDownSoft;
	public ScaleFunctionElements getScaleFunctionAccess() {
		return pScaleFunction;
	}
	
	public ParserRule getScaleFunctionRule() {
		return getScaleFunctionAccess().getRule();
	}

	//WaitFunction:
	//	name="wait";
	public WaitFunctionElements getWaitFunctionAccess() {
		return pWaitFunction;
	}
	
	public ParserRule getWaitFunctionRule() {
		return getWaitFunctionAccess().getRule();
	}

	//GenericFunction:
	//	name=ID;
	public GenericFunctionElements getGenericFunctionAccess() {
		return pGenericFunction;
	}
	
	public ParserRule getGenericFunctionRule() {
		return getGenericFunctionAccess().getRule();
	}

	//ScaleInInfra:
	//	name="scaleInInfra";
	public ScaleInInfraElements getScaleInInfraAccess() {
		return pScaleInInfra;
	}
	
	public ParserRule getScaleInInfraRule() {
		return getScaleInInfraAccess().getRule();
	}

	//ScaleOutInfra:
	//	name="scaleOutInfra";
	public ScaleOutInfraElements getScaleOutInfraAccess() {
		return pScaleOutInfra;
	}
	
	public ParserRule getScaleOutInfraRule() {
		return getScaleOutInfraAccess().getRule();
	}

	//ScaleUpInfra:
	//	name="scaleUpInfra";
	public ScaleUpInfraElements getScaleUpInfraAccess() {
		return pScaleUpInfra;
	}
	
	public ParserRule getScaleUpInfraRule() {
		return getScaleUpInfraAccess().getRule();
	}

	//ScaleDownInfra:
	//	name="scaleDownInfra";
	public ScaleDownInfraElements getScaleDownInfraAccess() {
		return pScaleDownInfra;
	}
	
	public ParserRule getScaleDownInfraRule() {
		return getScaleDownInfraAccess().getRule();
	}

	//ScaleInSoft:
	//	name="scaleInSoft";
	public ScaleInSoftElements getScaleInSoftAccess() {
		return pScaleInSoft;
	}
	
	public ParserRule getScaleInSoftRule() {
		return getScaleInSoftAccess().getRule();
	}

	//ScaleOutSoft:
	//	name="scaleOutSoft";
	public ScaleOutSoftElements getScaleOutSoftAccess() {
		return pScaleOutSoft;
	}
	
	public ParserRule getScaleOutSoftRule() {
		return getScaleOutSoftAccess().getRule();
	}

	//ScaleUpSoft:
	//	name="scaleUpSoft";
	public ScaleUpSoftElements getScaleUpSoftAccess() {
		return pScaleUpSoft;
	}
	
	public ParserRule getScaleUpSoftRule() {
		return getScaleUpSoftAccess().getRule();
	}

	//ScaleDownSoft:
	//	name="scaleDownSoft";
	public ScaleDownSoftElements getScaleDownSoftAccess() {
		return pScaleDownSoft;
	}
	
	public ParserRule getScaleDownSoftRule() {
		return getScaleDownSoftAccess().getRule();
	}

	//Param:
	//	value=INT;
	public ParamElements getParamAccess() {
		return pParam;
	}
	
	public ParserRule getParamRule() {
		return getParamAccess().getRule();
	}

	//terminal PARALLEL_SEPARATOR:
	//	"||";
	public TerminalRule getPARALLEL_SEPARATORRule() {
		return tPARALLEL_SEPARATOR;
	} 

	////Lexems
	//terminal LP:
	//	"(";
	public TerminalRule getLPRule() {
		return tLP;
	} 

	//terminal RP:
	//	")";
	public TerminalRule getRPRule() {
		return tRP;
	} 

	//terminal fragment LETTER:
	//	"$" | "A".."Z" | "a".."z" | "_";
	public TerminalRule getLETTERRule() {
		return tLETTER;
	} 

	//terminal fragment NUMBER:
	//	"0".."9";
	public TerminalRule getNUMBERRule() {
		return tNUMBER;
	} 

	//terminal SEQUENTIAL_SEPARATOR:
	//	";";
	public TerminalRule getSEQUENTIAL_SEPARATORRule() {
		return tSEQUENTIAL_SEPARATOR;
	} 

	//terminal COMMA:
	//	",";
	public TerminalRule getCOMMARule() {
		return tCOMMA;
	} 

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" . / * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\""))* "\"" | "\'" ("\\" .
	//	/ * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
