/*
 * generated by Xtext
 */
package org.elascript;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ElascriptRuntimeModule extends org.elascript.AbstractElascriptRuntimeModule {

}
