/*
 * generated by Xtext
 */
package org.elascript;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ElascriptStandaloneSetup extends ElascriptStandaloneSetupGenerated{

	public static void doSetup() {
		new ElascriptStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

