/**
 * generated by Xtext
 */
package emn.a1.elascript.ui.contentassist;

import emn.a1.elascript.ui.contentassist.AbstractElascriptProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class ElascriptProposalProvider extends AbstractElascriptProposalProvider {
}
