/*
 * generated by Xtext
 */
package org.elascript.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.elascript.ui.internal.ElascriptActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ElascriptExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ElascriptActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ElascriptActivator.getInstance().getInjector(ElascriptActivator.ORG_ELASCRIPT_ELASCRIPT);
	}
	
}
