/*
 * generated by Xtext
 */
package org.elascript.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ElascriptUiModule extends org.elascript.ui.AbstractElascriptUiModule {
	public ElascriptUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
