/**
 * generated by Xtext
 */
package emn.a1.elascript.ui.contentassist;

import emn.a1.elascript.ui.contentassist.AbstractElascriptProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class ElascriptProposalProvider extends AbstractElascriptProposalProvider {
}
