/*
 * generated by Xtext
 */
package emn.a1.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ElascriptUiModule extends emn.a1.ui.AbstractElascriptUiModule {
	public ElascriptUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
