/*
 * generated by Xtext
 */
package org.elascript.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class ElascriptGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class ScriptElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Script");
		private final Assignment cScriptStatementsAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cScriptStatementsStatementParserRuleCall_0 = (RuleCall)cScriptStatementsAssignment.eContents().get(0);
		
		//Script:
		//	scriptStatements+=Statement*;
		@Override public ParserRule getRule() { return rule; }

		//scriptStatements+=Statement*
		public Assignment getScriptStatementsAssignment() { return cScriptStatementsAssignment; }

		//Statement
		public RuleCall getScriptStatementsStatementParserRuleCall_0() { return cScriptStatementsStatementParserRuleCall_0; }
	}

	public class StatementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Statement");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cCommandParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cParallelParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Statement:
		//	Command | Parallel;
		@Override public ParserRule getRule() { return rule; }

		//Command | Parallel
		public Alternatives getAlternatives() { return cAlternatives; }

		//Command
		public RuleCall getCommandParserRuleCall_0() { return cCommandParserRuleCall_0; }

		//Parallel
		public RuleCall getParallelParserRuleCall_1() { return cParallelParserRuleCall_1; }
	}

	public class ParallelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Parallel");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cSPLITTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Assignment cStatementsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cStatementsStatementListParserRuleCall_1_0 = (RuleCall)cStatementsAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final RuleCall cPARALLEL_SEPARATORTerminalRuleCall_2_0 = (RuleCall)cGroup_2.eContents().get(0);
		private final Assignment cStatementsAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cStatementsStatementListParserRuleCall_2_1_0 = (RuleCall)cStatementsAssignment_2_1.eContents().get(0);
		private final RuleCall cJOINTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		
		//Parallel:
		//	SPLIT statements+=StatementList (PARALLEL_SEPARATOR statements+=StatementList)+ JOIN;
		@Override public ParserRule getRule() { return rule; }

		//SPLIT statements+=StatementList (PARALLEL_SEPARATOR statements+=StatementList)+ JOIN
		public Group getGroup() { return cGroup; }

		//SPLIT
		public RuleCall getSPLITTerminalRuleCall_0() { return cSPLITTerminalRuleCall_0; }

		//statements+=StatementList
		public Assignment getStatementsAssignment_1() { return cStatementsAssignment_1; }

		//StatementList
		public RuleCall getStatementsStatementListParserRuleCall_1_0() { return cStatementsStatementListParserRuleCall_1_0; }

		//(PARALLEL_SEPARATOR statements+=StatementList)+
		public Group getGroup_2() { return cGroup_2; }

		//PARALLEL_SEPARATOR
		public RuleCall getPARALLEL_SEPARATORTerminalRuleCall_2_0() { return cPARALLEL_SEPARATORTerminalRuleCall_2_0; }

		//statements+=StatementList
		public Assignment getStatementsAssignment_2_1() { return cStatementsAssignment_2_1; }

		//StatementList
		public RuleCall getStatementsStatementListParserRuleCall_2_1_0() { return cStatementsStatementListParserRuleCall_2_1_0; }

		//JOIN
		public RuleCall getJOINTerminalRuleCall_3() { return cJOINTerminalRuleCall_3; }
	}

	public class StatementListElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "StatementList");
		private final Assignment cStatementsAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cStatementsStatementParserRuleCall_0 = (RuleCall)cStatementsAssignment.eContents().get(0);
		
		//StatementList returns EList:
		//	statements+=Statement+;
		@Override public ParserRule getRule() { return rule; }

		//statements+=Statement+
		public Assignment getStatementsAssignment() { return cStatementsAssignment; }

		//Statement
		public RuleCall getStatementsStatementParserRuleCall_0() { return cStatementsStatementParserRuleCall_0; }
	}

	public class CommandElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Command");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameFunctionNameParserRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final RuleCall cLPTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Assignment cParamsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cParamsParamParserRuleCall_2_0 = (RuleCall)cParamsAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final RuleCall cCOMMATerminalRuleCall_3_0 = (RuleCall)cGroup_3.eContents().get(0);
		private final Assignment cParamsAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cParamsParamParserRuleCall_3_1_0 = (RuleCall)cParamsAssignment_3_1.eContents().get(0);
		private final RuleCall cRPTerminalRuleCall_4 = (RuleCall)cGroup.eContents().get(4);
		private final RuleCall cSEQUENTIAL_SEPARATORTerminalRuleCall_5 = (RuleCall)cGroup.eContents().get(5);
		
		//Command:
		//	name=FunctionName LP params+=Param (COMMA params+=Param)* RP SEQUENTIAL_SEPARATOR;
		@Override public ParserRule getRule() { return rule; }

		//name=FunctionName LP params+=Param (COMMA params+=Param)* RP SEQUENTIAL_SEPARATOR
		public Group getGroup() { return cGroup; }

		//name=FunctionName
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }

		//FunctionName
		public RuleCall getNameFunctionNameParserRuleCall_0_0() { return cNameFunctionNameParserRuleCall_0_0; }

		//LP
		public RuleCall getLPTerminalRuleCall_1() { return cLPTerminalRuleCall_1; }

		//params+=Param
		public Assignment getParamsAssignment_2() { return cParamsAssignment_2; }

		//Param
		public RuleCall getParamsParamParserRuleCall_2_0() { return cParamsParamParserRuleCall_2_0; }

		//(COMMA params+=Param)*
		public Group getGroup_3() { return cGroup_3; }

		//COMMA
		public RuleCall getCOMMATerminalRuleCall_3_0() { return cCOMMATerminalRuleCall_3_0; }

		//params+=Param
		public Assignment getParamsAssignment_3_1() { return cParamsAssignment_3_1; }

		//Param
		public RuleCall getParamsParamParserRuleCall_3_1_0() { return cParamsParamParserRuleCall_3_1_0; }

		//RP
		public RuleCall getRPTerminalRuleCall_4() { return cRPTerminalRuleCall_4; }

		//SEQUENTIAL_SEPARATOR
		public RuleCall getSEQUENTIAL_SEPARATORTerminalRuleCall_5() { return cSEQUENTIAL_SEPARATORTerminalRuleCall_5; }
	}

	public class FunctionNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "FunctionName");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final RuleCall cScaleParserRuleCall_0_0 = (RuleCall)cGroup_0.eContents().get(0);
		private final RuleCall cTypeParserRuleCall_0_1 = (RuleCall)cGroup_0.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//FunctionName:
		//	Scale Type | ID;
		@Override public ParserRule getRule() { return rule; }

		//Scale Type | ID
		public Alternatives getAlternatives() { return cAlternatives; }

		//Scale Type
		public Group getGroup_0() { return cGroup_0; }

		//Scale
		public RuleCall getScaleParserRuleCall_0_0() { return cScaleParserRuleCall_0_0; }

		//Type
		public RuleCall getTypeParserRuleCall_0_1() { return cTypeParserRuleCall_0_1; }

		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}

	public class ParamElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Param");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueINTTerminalRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//Param:
		//	value=INT;
		@Override public ParserRule getRule() { return rule; }

		//value=INT
		public Assignment getValueAssignment() { return cValueAssignment; }

		//INT
		public RuleCall getValueINTTerminalRuleCall_0() { return cValueINTTerminalRuleCall_0; }
	}

	public class ScaleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Scale");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSCALE_INTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cSCALE_OUTTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cSCALE_UPTerminalRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cSCALE_DOWNTerminalRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//Scale:
		//	SCALE_IN | SCALE_OUT | SCALE_UP | SCALE_DOWN;
		@Override public ParserRule getRule() { return rule; }

		//SCALE_IN | SCALE_OUT | SCALE_UP | SCALE_DOWN
		public Alternatives getAlternatives() { return cAlternatives; }

		//SCALE_IN
		public RuleCall getSCALE_INTerminalRuleCall_0() { return cSCALE_INTerminalRuleCall_0; }

		//SCALE_OUT
		public RuleCall getSCALE_OUTTerminalRuleCall_1() { return cSCALE_OUTTerminalRuleCall_1; }

		//SCALE_UP
		public RuleCall getSCALE_UPTerminalRuleCall_2() { return cSCALE_UPTerminalRuleCall_2; }

		//SCALE_DOWN
		public RuleCall getSCALE_DOWNTerminalRuleCall_3() { return cSCALE_DOWNTerminalRuleCall_3; }
	}

	public class TypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Type");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSOFTTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cINFTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Type:
		//	SOFT | INF;
		@Override public ParserRule getRule() { return rule; }

		//SOFT | INF
		public Alternatives getAlternatives() { return cAlternatives; }

		//SOFT
		public RuleCall getSOFTTerminalRuleCall_0() { return cSOFTTerminalRuleCall_0; }

		//INF
		public RuleCall getINFTerminalRuleCall_1() { return cINFTerminalRuleCall_1; }
	}
	
	
	private final ScriptElements pScript;
	private final StatementElements pStatement;
	private final ParallelElements pParallel;
	private final StatementListElements pStatementList;
	private final CommandElements pCommand;
	private final FunctionNameElements pFunctionName;
	private final ParamElements pParam;
	private final ScaleElements pScale;
	private final TerminalRule tSCALE_IN;
	private final TerminalRule tSCALE_OUT;
	private final TerminalRule tSCALE_UP;
	private final TerminalRule tSCALE_DOWN;
	private final TypeElements pType;
	private final TerminalRule tSOFT;
	private final TerminalRule tINF;
	private final TerminalRule tPARALLEL_SEPARATOR;
	private final TerminalRule tLP;
	private final TerminalRule tRP;
	private final TerminalRule tLETTER;
	private final TerminalRule tNUMBER;
	private final TerminalRule tSEQUENTIAL_SEPARATOR;
	private final TerminalRule tCOMMA;
	private final TerminalRule tSPLIT;
	private final TerminalRule tJOIN;
	
	private final Grammar grammar;

	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public ElascriptGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pScript = new ScriptElements();
		this.pStatement = new StatementElements();
		this.pParallel = new ParallelElements();
		this.pStatementList = new StatementListElements();
		this.pCommand = new CommandElements();
		this.pFunctionName = new FunctionNameElements();
		this.pParam = new ParamElements();
		this.pScale = new ScaleElements();
		this.tSCALE_IN = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "SCALE_IN");
		this.tSCALE_OUT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "SCALE_OUT");
		this.tSCALE_UP = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "SCALE_UP");
		this.tSCALE_DOWN = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "SCALE_DOWN");
		this.pType = new TypeElements();
		this.tSOFT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "SOFT");
		this.tINF = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "INF");
		this.tPARALLEL_SEPARATOR = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "PARALLEL_SEPARATOR");
		this.tLP = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "LP");
		this.tRP = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "RP");
		this.tLETTER = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "LETTER");
		this.tNUMBER = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "NUMBER");
		this.tSEQUENTIAL_SEPARATOR = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "SEQUENTIAL_SEPARATOR");
		this.tCOMMA = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "COMMA");
		this.tSPLIT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "SPLIT");
		this.tJOIN = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "JOIN");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.elascript.Elascript".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Script:
	//	scriptStatements+=Statement*;
	public ScriptElements getScriptAccess() {
		return pScript;
	}
	
	public ParserRule getScriptRule() {
		return getScriptAccess().getRule();
	}

	//Statement:
	//	Command | Parallel;
	public StatementElements getStatementAccess() {
		return pStatement;
	}
	
	public ParserRule getStatementRule() {
		return getStatementAccess().getRule();
	}

	//Parallel:
	//	SPLIT statements+=StatementList (PARALLEL_SEPARATOR statements+=StatementList)+ JOIN;
	public ParallelElements getParallelAccess() {
		return pParallel;
	}
	
	public ParserRule getParallelRule() {
		return getParallelAccess().getRule();
	}

	//StatementList returns EList:
	//	statements+=Statement+;
	public StatementListElements getStatementListAccess() {
		return pStatementList;
	}
	
	public ParserRule getStatementListRule() {
		return getStatementListAccess().getRule();
	}

	//Command:
	//	name=FunctionName LP params+=Param (COMMA params+=Param)* RP SEQUENTIAL_SEPARATOR;
	public CommandElements getCommandAccess() {
		return pCommand;
	}
	
	public ParserRule getCommandRule() {
		return getCommandAccess().getRule();
	}

	//FunctionName:
	//	Scale Type | ID;
	public FunctionNameElements getFunctionNameAccess() {
		return pFunctionName;
	}
	
	public ParserRule getFunctionNameRule() {
		return getFunctionNameAccess().getRule();
	}

	//Param:
	//	value=INT;
	public ParamElements getParamAccess() {
		return pParam;
	}
	
	public ParserRule getParamRule() {
		return getParamAccess().getRule();
	}

	//Scale:
	//	SCALE_IN | SCALE_OUT | SCALE_UP | SCALE_DOWN;
	public ScaleElements getScaleAccess() {
		return pScale;
	}
	
	public ParserRule getScaleRule() {
		return getScaleAccess().getRule();
	}

	//terminal SCALE_IN:
	//	"ScaleIn";
	public TerminalRule getSCALE_INRule() {
		return tSCALE_IN;
	} 

	//terminal SCALE_OUT:
	//	"ScaleOut";
	public TerminalRule getSCALE_OUTRule() {
		return tSCALE_OUT;
	} 

	//terminal SCALE_UP:
	//	"ScaleUp";
	public TerminalRule getSCALE_UPRule() {
		return tSCALE_UP;
	} 

	//terminal SCALE_DOWN:
	//	"ScaleDown";
	public TerminalRule getSCALE_DOWNRule() {
		return tSCALE_DOWN;
	} 

	//Type:
	//	SOFT | INF;
	public TypeElements getTypeAccess() {
		return pType;
	}
	
	public ParserRule getTypeRule() {
		return getTypeAccess().getRule();
	}

	//terminal SOFT:
	//	"Soft";
	public TerminalRule getSOFTRule() {
		return tSOFT;
	} 

	//terminal INF:
	//	"Inf";
	public TerminalRule getINFRule() {
		return tINF;
	} 

	//terminal PARALLEL_SEPARATOR:
	//	"||";
	public TerminalRule getPARALLEL_SEPARATORRule() {
		return tPARALLEL_SEPARATOR;
	} 

	////Lexems
	//terminal LP:
	//	"(";
	public TerminalRule getLPRule() {
		return tLP;
	} 

	//terminal RP:
	//	")";
	public TerminalRule getRPRule() {
		return tRP;
	} 

	//terminal fragment LETTER:
	//	"$" | "A".."Z" | "a".."z" | "_";
	public TerminalRule getLETTERRule() {
		return tLETTER;
	} 

	//terminal fragment NUMBER:
	//	"0".."9";
	public TerminalRule getNUMBERRule() {
		return tNUMBER;
	} 

	//terminal SEQUENTIAL_SEPARATOR:
	//	";";
	public TerminalRule getSEQUENTIAL_SEPARATORRule() {
		return tSEQUENTIAL_SEPARATOR;
	} 

	//terminal COMMA:
	//	",";
	public TerminalRule getCOMMARule() {
		return tCOMMA;
	} 

	//terminal SPLIT:
	//	"[";
	public TerminalRule getSPLITRule() {
		return tSPLIT;
	} 

	//terminal JOIN:
	//	"]";
	public TerminalRule getJOINRule() {
		return tJOIN;
	} 

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" . / * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\""))* "\"" | "\'" ("\\" .
	//	/ * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
