/**
 * generated by Xtext
 */
package emn.a1.elascript.validation;

import emn.a1.elascript.validation.AbstractElascriptValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class ElascriptValidator extends AbstractElascriptValidator {
}
