/*
* generated by Xtext
*/
package emn.a1.elascript.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import emn.a1.elascript.services.ElascriptGrammarAccess;

public class ElascriptParser extends AbstractContentAssistParser {
	
	@Inject
	private ElascriptGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected emn.a1.elascript.ui.contentassist.antlr.internal.InternalElascriptParser createParser() {
		emn.a1.elascript.ui.contentassist.antlr.internal.InternalElascriptParser result = new emn.a1.elascript.ui.contentassist.antlr.internal.InternalElascriptParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getStatementAccess().getAlternatives(), "rule__Statement__Alternatives");
					put(grammarAccess.getCommandAccess().getAlternatives_0(), "rule__Command__Alternatives_0");
					put(grammarAccess.getScaleFunctionAccess().getAlternatives(), "rule__ScaleFunction__Alternatives");
					put(grammarAccess.getScriptAccess().getGroup(), "rule__Script__Group__0");
					put(grammarAccess.getParallelAccess().getGroup(), "rule__Parallel__Group__0");
					put(grammarAccess.getParallelAccess().getGroup_2(), "rule__Parallel__Group_2__0");
					put(grammarAccess.getCommandAccess().getGroup(), "rule__Command__Group__0");
					put(grammarAccess.getCommandAccess().getGroup_3(), "rule__Command__Group_3__0");
					put(grammarAccess.getScriptAccess().getBeginScriptAssignment_0(), "rule__Script__BeginScriptAssignment_0");
					put(grammarAccess.getScriptAccess().getScriptStatementAssignment_1(), "rule__Script__ScriptStatementAssignment_1");
					put(grammarAccess.getScriptAccess().getEndScriptAssignment_2(), "rule__Script__EndScriptAssignment_2");
					put(grammarAccess.getBeginScriptAccess().getNameAssignment(), "rule__BeginScript__NameAssignment");
					put(grammarAccess.getEndScriptAccess().getNameAssignment(), "rule__EndScript__NameAssignment");
					put(grammarAccess.getParallelAccess().getBeginParallelAssignment_0(), "rule__Parallel__BeginParallelAssignment_0");
					put(grammarAccess.getParallelAccess().getStatementListsAssignment_1(), "rule__Parallel__StatementListsAssignment_1");
					put(grammarAccess.getParallelAccess().getStatementListsAssignment_2_1(), "rule__Parallel__StatementListsAssignment_2_1");
					put(grammarAccess.getParallelAccess().getEndParallelAssignment_3(), "rule__Parallel__EndParallelAssignment_3");
					put(grammarAccess.getBeginParallelAccess().getNameAssignment(), "rule__BeginParallel__NameAssignment");
					put(grammarAccess.getEndParallelAccess().getNameAssignment(), "rule__EndParallel__NameAssignment");
					put(grammarAccess.getStatementListAccess().getStatementsAssignment(), "rule__StatementList__StatementsAssignment");
					put(grammarAccess.getCommandAccess().getParamsAssignment_2(), "rule__Command__ParamsAssignment_2");
					put(grammarAccess.getCommandAccess().getParamsAssignment_3_1(), "rule__Command__ParamsAssignment_3_1");
					put(grammarAccess.getWaitFunctionAccess().getNameAssignment(), "rule__WaitFunction__NameAssignment");
					put(grammarAccess.getGenericFunctionAccess().getNameAssignment(), "rule__GenericFunction__NameAssignment");
					put(grammarAccess.getScaleInInfraAccess().getNameAssignment(), "rule__ScaleInInfra__NameAssignment");
					put(grammarAccess.getScaleOutInfraAccess().getNameAssignment(), "rule__ScaleOutInfra__NameAssignment");
					put(grammarAccess.getScaleUpInfraAccess().getNameAssignment(), "rule__ScaleUpInfra__NameAssignment");
					put(grammarAccess.getScaleDownInfraAccess().getNameAssignment(), "rule__ScaleDownInfra__NameAssignment");
					put(grammarAccess.getScaleInSoftAccess().getNameAssignment(), "rule__ScaleInSoft__NameAssignment");
					put(grammarAccess.getScaleOutSoftAccess().getNameAssignment(), "rule__ScaleOutSoft__NameAssignment");
					put(grammarAccess.getScaleUpSoftAccess().getNameAssignment(), "rule__ScaleUpSoft__NameAssignment");
					put(grammarAccess.getScaleDownSoftAccess().getNameAssignment(), "rule__ScaleDownSoft__NameAssignment");
					put(grammarAccess.getParamAccess().getValueAssignment(), "rule__Param__ValueAssignment");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			emn.a1.elascript.ui.contentassist.antlr.internal.InternalElascriptParser typedParser = (emn.a1.elascript.ui.contentassist.antlr.internal.InternalElascriptParser) parser;
			typedParser.entryRuleScript();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public ElascriptGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ElascriptGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
